2019-12-19 19:16:26,172 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 281407ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 08:12:45,233 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 43258297ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 09:30:03,041 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 4637358ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 10:44:31,991 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 4468920ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 12:17:04,366 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 411373ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 12:24:01,940 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 397480ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 12:34:20,759 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 578792ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 12:49:56,771 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 813983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

