2019-12-20 16:01:12,307 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 233504ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 16:33:52,103 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 159481ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-20 22:32:54,294 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 10419155ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-21 11:09:56,407 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 43261553ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-22 09:00:03,084 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 78605808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-23 15:47:44,688 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 110861518ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-23 22:43:38,627 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 23592935ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-24 00:49:51,348 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 1906143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-24 01:10:54,569 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 1223139ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-24 01:18:02,070 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 387479ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-24 01:48:18,448 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 916224ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

2019-12-24 10:52:17,132 ERROR 44029 nodejs.ClusterClientNoResponseError: client no response in 30232095ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/pengzefan/learn/shopping-system/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
name: "ClusterClientNoResponseError"
pid: 44029
hostname: C02Y81Q2JG5L

